language: python
dist: xenial
cache:
  pip: true
python:
- 3.6
- 3.7
- 3.8
services:
- docker
install:
- python -m pip install --upgrade pip
- pip install .
- pip install --upgrade .[test]
matrix:
  include:
  - os: windows
    language: sh
    python: '3.6'
    cache:
    - pip: true
    before_install:
    - choco install python --version 3.6.8
    - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
  - name: Linting & formatting check
    python: '3.6'
    script:
    - ./travis/linter.sh
  - name: ONNX artifact
    python: '3.6'
    script:
    - ./travis/onnx_integration_tests.sh
  - name: Pytorch Artifact
    python: '3.6'
    script:
    - ./travis/pytorch_integration_tests.sh
  - name: Tensorflow v2.2 Artifact
    python: '3.6'
    script:
    - ./travis/tensorflow_v2.2_integration_tests.sh
  - name: API Server Integration Tests
    python: '3.7'
    script:
    - ./travis/integration_tests.sh
  - name: CoreML artifact (minimal)
    os: osx
    osx_image: xcode12
    language: minimal
    install:
    - ./travis/install_python36_osx.sh
    - export PATH=${HOME}/miniconda/bin:${PATH}
    - hash -r
    - python -m pip install --upgrade pip
    - pip install .
    - pip install --upgrade .[test]
    script:
    - ./travis/coreml_integration_tests.sh
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
